"""The inference-time embedding fit (CONCEPT.md §5.5, §15).

Two requirements from §15: the fit is deterministic under a fixed seed, and the
**joint** fit of several players converges on a synthetic case with a known
answer.

The synthetic case is built so the answer is known by construction: a frozen
network, a chosen set of "true" vectors ``v*``, and labels taken to be what the
network itself predicts under ``v*``. The loss ``v*`` achieves on those labels
is then the target the fit has to reach, and it is reachable because ``v*``
reaches it.

The fit is full-batch gradient descent with no sampling anywhere, so
determinism here is exact, not statistical.
"""

import torch

from nets.embedding_net import (
    OpponentEmbeddingNet, evaluate_ce, fit_embeddings,
)
from nets.features import collate, hand_tokens
from tests.g1_fixtures import (
    MAX_PLAYERS, N_ACTIONS, NET_CFG, make_pool, observer_seat, play,
    session_specs, slot_of_seat,
)

N_SLOTS = 4


def _synthetic_case(n_hands=16, seed=0):
    """Frozen net + a batch whose labels were generated by known vectors."""
    pool = make_pool()
    records = play(pool, session_specs([0, 1, 2, 3], N_SLOTS, n_hands, seed=seed))
    hands = [
        hand_tokens(r, observer_seat(N_SLOTS, h), slot_of_seat(N_SLOTS, h),
                    MAX_PLAYERS, N_ACTIONS)
        for h, r in enumerate(records)
    ]
    batch = collate([h for h in hands if len(h) > 0])

    torch.manual_seed(3)
    net = OpponentEmbeddingNet(NET_CFG, N_ACTIONS, MAX_PLAYERS,
                               n_members=len(pool)).eval()

    true_vectors = torch.randn(N_SLOTS, net.d_emb) * 2.0
    with torch.no_grad():
        logits = net(batch, net.slot_emb(batch, true_vectors))
        masked = logits.masked_fill(~batch["legal"],
                                    torch.finfo(logits.dtype).min)
        batch["action"] = masked.argmax(dim=-1)
    return net, batch, true_vectors


def test_the_joint_fit_reaches_the_loss_of_the_generating_vectors():
    net, batch, true_vectors = _synthetic_case()

    ce_star, _ = evaluate_ce(net, batch, net.slot_emb(batch, true_vectors))
    ce_zero, _ = evaluate_ce(net, batch, net.zero_emb(batch))

    zeros = torch.zeros(N_SLOTS, net.d_emb)
    fitted = fit_embeddings(net, batch, N_SLOTS, steps=300, lr=0.1, reg=0.0,
                            init=zeros)
    ce_fit, _ = evaluate_ce(net, batch, net.slot_emb(batch, fitted))

    assert ce_star < ce_zero, "the synthetic case is degenerate"
    assert ce_fit < ce_zero, "the fit did not improve on e = 0 at all"
    assert ce_fit <= ce_star + 0.05, (
        f"the joint fit did not converge: {ce_fit:.4f} vs the generating "
        f"vectors' {ce_star:.4f}")


def test_the_fit_is_deterministic():
    net, batch, _ = _synthetic_case()
    kwargs = dict(steps=25, lr=0.1, reg=0.01,
                  init=torch.zeros(N_SLOTS, net.d_emb))
    a = fit_embeddings(net, batch, N_SLOTS, **kwargs)
    b = fit_embeddings(net, batch, N_SLOTS, **kwargs)
    assert torch.equal(a, b)


def test_all_players_are_fitted_and_they_are_fitted_apart():
    """§5.3: the embeddings at a table are coupled, so they are fitted jointly —
    not one at a time, and not to the same value."""
    net, batch, _ = _synthetic_case()
    fitted = fit_embeddings(net, batch, N_SLOTS, steps=200, lr=0.1, reg=0.0,
                            init=torch.zeros(N_SLOTS, net.d_emb))
    assert fitted.shape == (N_SLOTS, net.d_emb)
    assert (fitted.norm(dim=-1) > 1e-6).all(), "a slot was never moved"
    for i in range(N_SLOTS):
        for j in range(i + 1, N_SLOTS):
            assert not torch.allclose(fitted[i], fitted[j], atol=1e-4)


def test_k_zero_is_the_ablation_and_returns_the_initialisation_untouched():
    """§5.4's mandatory ablation: the amortised head's output, no gradient fit."""
    net, batch, _ = _synthetic_case()
    init = net.amortised_init(batch, N_SLOTS)
    out = fit_embeddings(net, batch, N_SLOTS, steps=0, lr=0.1, reg=0.01,
                         init=init)
    assert torch.equal(out, init)


def test_the_fit_leaves_the_network_weights_alone():
    """Transformer weights are frozen during the fit (§5.5), and their
    `requires_grad` flags come back exactly as they were."""
    net, batch, _ = _synthetic_case()
    before = [p.detach().clone() for p in net.parameters()]
    flags = [p.requires_grad for p in net.parameters()]

    fit_embeddings(net, batch, N_SLOTS, steps=10, lr=0.1, reg=0.01,
                   init=torch.zeros(N_SLOTS, net.d_emb))

    for p, was, flag in zip(net.parameters(), before, flags):
        assert torch.equal(p.detach(), was)
        assert p.requires_grad == flag
        assert p.grad is None or float(p.grad.abs().sum()) == 0.0


def test_a_slot_with_no_observed_decision_keeps_its_cold_start():
    """§5.5: cold start is the zero vector, and nothing invents one for a
    player who never acted."""
    net, batch, _ = _synthetic_case()
    n_slots = N_SLOTS + 2                       # two slots that never appear
    init = net.amortised_init(batch, n_slots)
    assert float(init[N_SLOTS:].abs().sum()) == 0.0

    fitted = fit_embeddings(net, batch, n_slots, steps=20, lr=0.1, reg=0.01,
                            init=init)
    assert float(fitted[N_SLOTS:].abs().sum()) == 0.0


def test_the_showdown_terms_reach_the_fitted_vector():
    """§5.1a's second half, and the one that is easy to miss.

    v8's embedding is a latent found by gradient descent **at deployment**, so a
    training-only showdown probe would shape the weights and then be optimised
    straight back out of the vector. The showdown terms have to be in the fit
    objective, and this is what checks that they are.
    """
    net, batch, _ = _synthetic_case()
    assert float(batch["showdown_mask"].sum()) > 0, "no showdown in the fixture"

    weights = {"showdown_strength": 3.0, "showdown_class": 1.0}
    kwargs = dict(steps=80, lr=0.1, reg=0.0,
                  init=torch.zeros(N_SLOTS, net.d_emb))
    without = fit_embeddings(net, batch, N_SLOTS, weights=None, **kwargs)
    with_sd = fit_embeddings(net, batch, N_SLOTS, weights=weights, **kwargs)

    assert not torch.allclose(without, with_sd, atol=1e-4), (
        "the showdown terms changed nothing about the fitted vector")

    with torch.no_grad():
        def showdown_loss(vectors):
            hidden = net.hidden(batch, net.slot_emb(batch, vectors))
            s, c = net.showdown_losses(hidden, batch)
            return float((weights["showdown_strength"] * s
                          + weights["showdown_class"] * c).detach())
    assert showdown_loss(with_sd) < showdown_loss(without), (
        "fitting with the showdown terms did not explain the showdowns better")


def test_zero_showdown_weights_reproduce_the_action_only_fit():
    net, batch, _ = _synthetic_case()
    kwargs = dict(steps=20, lr=0.1, reg=0.01,
                  init=torch.zeros(N_SLOTS, net.d_emb))
    a = fit_embeddings(net, batch, N_SLOTS, weights=None, **kwargs)
    b = fit_embeddings(net, batch, N_SLOTS,
                       weights={"showdown_strength": 0.0,
                                "showdown_class": 0.0}, **kwargs)
    assert torch.equal(a, b)


def test_regularisation_pulls_the_vectors_toward_zero():
    net, batch, _ = _synthetic_case()
    kwargs = dict(steps=60, lr=0.1, init=torch.zeros(N_SLOTS, net.d_emb))
    loose = fit_embeddings(net, batch, N_SLOTS, reg=0.0, **kwargs)
    tight = fit_embeddings(net, batch, N_SLOTS, reg=5.0, **kwargs)
    assert float(tight.norm()) < float(loose.norm())
