"""
Timing benchmark for the v5 pipeline.

Runs the REAL pipeline (`pipeline.py`) end-to-end -- GTO data generation ->
GTO training -> opponent data generation -> opponent training -> MCTS self-play
collection + training -- and measures the three long phases:

    phase 1 (gto)       : GTO data generation + GTO head training
    phase 2 (opponent)  : opponent data generation + opponent_action training
    phase 3 (mcts)      : MCTS self-play collection + MCTS training

It sweeps three axes and reports how each phase scales:

    * parallelism P in {1, 2, 4}  (drives dataset.n_workers, opponent_data.n_workers,
                                    mcts_train.n_workers simultaneously -- all three stages)
    * agent size     : base (as now), half (x0.5 width), big (x1.5 width)
    * device         : GPU first (9 runs), then CPU (9 runs)

The CPU runs use the SAME 9 configurations, each phase capped at 2x the wall-clock
of its GPU counterpart -- a phase that exceeds the cap is killed and the rest of
that measurement is skipped.

Everything is production-like; only the SCALE (iteration counts) is reduced so the
whole sweep finishes in a reasonable time. Multi-agent is preserved.

Design notes
------------
* Each measurement runs the pipeline as THREE separate subprocesses (one per
  phase, chained through on-disk checkpoints). Separate subprocesses give clean
  per-phase wall-clock AND let the CPU run kill a single phase on the 2x cap.
* The pipeline reads `config.json` next to itself, so the benchmark BACKS UP the
  production config, writes a scaled config per phase, and RESTORES the backup at
  the end (in a finally block). The backup file is left on disk so it can be
  restored by hand if the benchmark crashes mid-run.
* GPU vs CPU is selected per subprocess via the CUDA_VISIBLE_DEVICES env var
  (empty string -> torch.cuda.is_available() is False -> pipeline picks "cpu").
  pipeline.py is NOT modified.
* The console shows ONLY progress (which of the 18 stages is running). Detailed
  per-phase timings go to a log file whose path is printed at startup. Each
  pipeline subprocess's own stdout/stderr is redirected to a raw log file (not
  the console).

Tuning: the SCALE_* and SIZES / PARALLELISM constants below are the only knobs.
Bump them if you want a heavier (more representative) or lighter (faster) sweep.

Run on the target machine (32 GB RAM / 4 cores / RTX 2060 Super 8 GB, Windows):

    python time_bench.py
"""

import os
import sys
import json
import copy
import time
import shutil
import signal
import subprocess
from datetime import datetime


# --------------------------- Tunable scale ---------------------------
# Agent width variants: (name, d_model, n_heads, n_kv_heads, d_ff).
# head_dim is kept at 32 and n_kv_heads divides n_heads for all sizes.
SIZES = [
    ("base", 256, 8, 2, 512),   # as now
    ("big",  384, 12, 3, 768),  # x1.5 width
]
PARALLELISM = [2, 4, 16, 32, 64, 128]         # applied to all three stages' n_workers

# Phase 1 -- GTO data gen + training
SCALE_N_SCENARIOS = 3          # >= max(PARALLELISM)*2 so the gen pool engages
SCALE_MC_ITERATIONS = 100       # solver Monte-Carlo iters (prod: 1000)
SCALE_COMBO_RESPONSE_ITERS = 8  # solver combo-response iters (prod: 30)
SCALE_GTO_EPOCHS = 1
SCALE_GTO_BATCH = 64            # kept large so the GPU is meaningfully loaded

# Phase 2 -- opponent data gen + training
SCALE_OPP_N_HANDS = 160
SCALE_OPP_MAX_PLAYERS = 3       # smaller tables -> faster, still multi-player
SCALE_OPP_BATCH = 64
SCALE_OPP_EPOCHS = 1

# Phase 3 -- MCTS collect + train
SCALE_MCTS_N_SIMULATIONS = 120  # prod: 3000 (within-tree batch_size stays 16)
SCALE_MCTS_EQUITY_ITERS = 200
SCALE_MCTS_N_HANDS = 120
SCALE_MCTS_CYCLES = 1
SCALE_MCTS_BATCH = 32
SCALE_MCTS_EPOCHS = 1
SCALE_MCTS_MIN_PLAYERS = 2
SCALE_MCTS_MAX_PLAYERS = 3

SERVER_MAX_BATCH = 256
SERVER_LINGER_MS = 2

N_AGENTS = 2                    # multi-agent, scaled down from prod's 5

# Safety / timeout
GPU_SAFETY_CAP_S = 3600         # hard ceiling per GPU phase (hang guard)
CPU_CAP_MULTIPLIER = 2.0        # CPU phase cap = this x matching GPU phase time
CPU_FALLBACK_CAP_S = 900        # used when the GPU baseline phase didn't finish


# Working directories under data/<version>/ that are WIPED before each
# measurement (regenerated by the pipeline). Results/raw logs live elsewhere.
_BENCH_NAME = "bench"           # pipeline experiment name -> data/<v>/bench
_BENCH_AGENTS = "bench_agents"  # multi_agent save_dir -> data/<v>/bench_agents


def _build_scaled_config(prod_cfg, size, n_workers):
    """Return a deep-copied, scaled, multi-agent config for one (size, P).

    `size` is one tuple from SIZES. The pipeline `pipeline` flags are set per
    phase later by `_set_phase_flags`.
    """
    name, d_model, n_heads, n_kv_heads, d_ff = size
    cfg = copy.deepcopy(prod_cfg)

    cfg["name"] = _BENCH_NAME
    cfg["agent_dir"] = ""  # start from random init (faithful cold start)

    # Architecture: scale width only; keep prod layer counts / max_players.
    arch = cfg["architecture"]
    arch["d_model"] = d_model
    arch["n_heads"] = n_heads
    arch["n_kv_heads"] = n_kv_heads
    arch["d_ff"] = d_ff

    # Multi-agent: keep the first N_AGENTS (with their modifiers), local save dir.
    ma = cfg["multi_agent"]
    ma["agents"] = ma["agents"][:N_AGENTS]
    ma["save_dir"] = _BENCH_AGENTS
    ma["skip_training"] = []

    # Dataset: always regenerate fresh (no cached dir), parallel gen via P.
    ds = cfg["dataset"]
    ds["dataset_dir"] = ""
    ds["save_dir"] = ""
    ds["n_scenarios"] = SCALE_N_SCENARIOS
    ds["n_workers"] = n_workers

    # Solver: lighter Monte-Carlo so generation is fast but representative.
    sv = cfg["solver"]
    sv["mc_iterations"] = SCALE_MC_ITERATIONS
    sv["combo_response_iters"] = SCALE_COMBO_RESPONSE_ITERS

    # GTO training: 1 epoch, decent batch. Phase 1 runs only gto_predict
    # (combined) + modelling (see _set_phase_flags); we still scale gto_ev/
    # gto_probs configs harmlessly in case those flags are re-enabled.
    for k in ("gto_ev_train", "gto_probs_train", "gto_train", "modelling_train"):
        cfg[k]["epochs"] = SCALE_GTO_EPOCHS
        cfg[k]["batch_size"] = SCALE_GTO_BATCH

    # Opponent data: small, parallel via P, agents come from our local save dir.
    opp = cfg["opponent_data"]
    opp["agents_dir"] = _BENCH_AGENTS
    opp["save_dir"] = ""            # fresh per run -> always timed
    opp["n_hands"] = SCALE_OPP_N_HANDS
    opp["max_players"] = SCALE_OPP_MAX_PLAYERS
    opp["n_player_pool"] = max(SCALE_OPP_MAX_PLAYERS * 2, 4)
    opp["n_workers"] = n_workers
    opp["server_max_batch"] = SERVER_MAX_BATCH
    opp["server_linger_ms"] = SERVER_LINGER_MS

    cfg["opponent_action_train"]["epochs"] = SCALE_OPP_EPOCHS
    cfg["opponent_action_train"]["batch_size"] = SCALE_OPP_BATCH

    # MCTS: small search/collection; within-tree batch_size stays 16 (prod).
    mc = cfg["mcts"]
    mc["n_simulations"] = SCALE_MCTS_N_SIMULATIONS
    mc["n_equity_iters"] = SCALE_MCTS_EQUITY_ITERS
    mc["batch_size"] = 16

    mt = cfg["mcts_train"]
    mt["n_cycles"] = SCALE_MCTS_CYCLES
    mt["n_hands_per_cycle"] = SCALE_MCTS_N_HANDS
    mt["batch_size"] = SCALE_MCTS_BATCH
    mt["epochs"] = SCALE_MCTS_EPOCHS
    mt["min_players"] = SCALE_MCTS_MIN_PLAYERS
    mt["max_players"] = SCALE_MCTS_MAX_PLAYERS
    mt["save_every_cycles"] = 1
    mt["n_workers"] = n_workers
    mt["server_max_batch"] = SERVER_MAX_BATCH
    mt["server_linger_ms"] = SERVER_LINGER_MS
    mt["examples_dir"] = ""        # force cyclic collect->train (not pre-baked)

    return cfg


def _set_phase_flags(cfg, phase):
    """Enable only the pipeline flags for one phase (1=gto, 2=opp, 3=mcts)."""
    flags = {
        "run_gto_ev": False, "run_gto_probs": False, "run_gto_training": False,
        "run_modelling": False, "run_opponent_data": False,
        "run_opponent_action_train": False, "run_mcts_train": False,
        "run_evaluation": False, "run_slumbot_eval": False,
    }
    if phase == 1:
        flags["run_gto_training"] = True
        flags["run_modelling"] = True
    elif phase == 2:
        flags["run_opponent_data"] = True
        flags["run_opponent_action_train"] = True
    elif phase == 3:
        flags["run_mcts_train"] = True
    cfg["pipeline"] = flags
    return cfg


PHASE_NAMES = {1: "gto", 2: "opponent", 3: "mcts"}


def run_benchmark():
    """Run the full 18-stage timing sweep. No parameters; all knobs are the
    module-level SCALE_*/SIZES/PARALLELISM constants above."""
    v5_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(v5_dir, "config.json")
    pipeline_path = os.path.join(v5_dir, "pipeline.py")
    version = os.path.basename(v5_dir)                       # "v5"
    project_root = os.path.dirname(os.path.dirname(v5_dir))  # ContinuousLearning
    data_dir = os.path.join(project_root, "data", version)

    ts = datetime.now().strftime("%Y_%m_%d_%H_%M_%S")

    # Results / raw logs live OUTSIDE the wiped working dirs.
    results_dir = os.path.join(data_dir, "bench_results", ts)
    raw_dir = os.path.join(results_dir, "raw")
    os.makedirs(raw_dir, exist_ok=True)
    detail_log_path = os.path.join(results_dir, "time_bench.log")

    # Back up the production config; it is restored in `finally`.
    backup_path = os.path.join(v5_dir, f"config.prod_backup_{ts}.json")
    shutil.copyfile(config_path, backup_path)
    with open(backup_path, "r", encoding="utf-8") as f:
        prod_cfg = json.load(f)

    _log_fh = open(detail_log_path, "a", encoding="utf-8")

    def log_detail(msg):
        stamp = datetime.now().strftime("%H:%M:%S")
        _log_fh.write(f"[{stamp}] {msg}\n")
        _log_fh.flush()

    def progress(msg):
        # The ONLY thing printed to the console.
        print(msg, flush=True)

    progress(f"time_bench: detailed log -> {detail_log_path}")
    progress(f"time_bench: config backup -> {backup_path}")
    log_detail("=== time_bench start ===")
    log_detail(f"config backup: {backup_path}")
    log_detail(f"sizes={[s[0] for s in SIZES]} parallelism={PARALLELISM} "
               f"n_agents={N_AGENTS}")
    log_detail(f"scale: n_scenarios={SCALE_N_SCENARIOS} mc_iters={SCALE_MC_ITERATIONS} "
               f"opp_hands={SCALE_OPP_N_HANDS} mcts_sims={SCALE_MCTS_N_SIMULATIONS} "
               f"mcts_hands={SCALE_MCTS_N_HANDS} cycles={SCALE_MCTS_CYCLES}")

    # Best-effort GPU detection (purely informational for the log).
    try:
        out = subprocess.run(
            [sys.executable, "-c", "import torch;print(torch.cuda.is_available())"],
            cwd=v5_dir, capture_output=True, text=True, timeout=120)
        cuda_ok = "True" in out.stdout
    except Exception:
        cuda_ok = False
    log_detail(f"torch.cuda.is_available()={cuda_ok}")
    if not cuda_ok:
        progress("WARNING: CUDA not detected -- 'GPU' runs will execute on CPU "
                 "(see log).")
        log_detail("WARNING: CUDA not available; GPU half runs on CPU, CPU caps "
                   "still derived from the GPU-half timings.")

    def kill_tree(proc):
        if proc.poll() is not None:
            return
        try:
            if os.name == "nt":
                subprocess.run(["taskkill", "/F", "/T", "/PID", str(proc.pid)],
                               stdout=subprocess.DEVNULL,
                               stderr=subprocess.DEVNULL)
            else:
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
        except Exception:
            try:
                proc.kill()
            except Exception:
                pass

    def wipe_working_dirs():
        for d in (os.path.join(data_dir, _BENCH_NAME),
                  os.path.join(data_dir, _BENCH_AGENTS)):
            shutil.rmtree(d, ignore_errors=True)

    def run_phase(cfg, phase, use_gpu, timeout_s, raw_path):
        """Write the per-phase config, launch the pipeline subprocess, time it.

        Returns (status, elapsed_seconds): status in {ok, error, timeout}.
        """
        _set_phase_flags(cfg, phase)
        with open(config_path, "w", encoding="utf-8") as f:
            json.dump(cfg, f, indent=4)

        env = dict(os.environ)
        env["PYTHONUNBUFFERED"] = "1"
        # Force UTF-8 for the child's stdout/stderr -- pipeline logs may contain
        # non-ASCII, which crashes on a Windows cp1251 console.
        env["PYTHONIOENCODING"] = "utf-8"
        if not use_gpu:
            env["CUDA_VISIBLE_DEVICES"] = ""  # force CPU device in the pipeline

        popen_kw = dict(cwd=v5_dir, env=env)
        if os.name == "nt":
            popen_kw["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP
        else:
            popen_kw["start_new_session"] = True

        t0 = time.perf_counter()
        with open(raw_path, "a", encoding="utf-8") as raw:
            raw.write(f"\n===== phase={PHASE_NAMES[phase]} gpu={use_gpu} "
                      f"timeout={timeout_s} =====\n")
            raw.flush()
            proc = subprocess.Popen([sys.executable, "pipeline.py"],
                                    stdout=raw, stderr=subprocess.STDOUT,
                                    **popen_kw)
            try:
                rc = proc.wait(timeout=timeout_s)
            except subprocess.TimeoutExpired:
                kill_tree(proc)
                try:
                    proc.wait(timeout=30)
                except Exception:
                    pass
                return "timeout", time.perf_counter() - t0
        elapsed = time.perf_counter() - t0
        return ("ok" if rc == 0 else "error"), elapsed

    gpu_results = {}   # (size_name, P) -> {phase: {"status","t"}}
    cpu_results = {}   # (size_name, P) -> {phase: {"status","t","cap"}}
    stage = 0
    total_stages = 2 * len(SIZES) * len(PARALLELISM)

    try:
        # -- Pass 1: GPU (no per-phase cap beyond the safety ceiling) --
        for size in SIZES:
            for P in PARALLELISM:
                stage += 1
                size_name = size[0]
                progress(f"[{stage}/{total_stages}] GPU  size={size_name} P={P} "
                         f"-- starting")
                log_detail(f"--- STAGE {stage}/{total_stages} | GPU | "
                           f"size={size_name} | P={P} ---")
                wipe_working_dirs()
                cfg = _build_scaled_config(prod_cfg, size, P)
                per_phase = {}
                for phase in (1, 2, 3):
                    raw_path = os.path.join(
                        raw_dir, f"s{stage:02d}_gpu_{size_name}_P{P}_"
                                 f"p{phase}_{PHASE_NAMES[phase]}.log")
                    # Skip later phases if an earlier one failed (chain broken).
                    if any(per_phase.get(p, {}).get("status") not in (None, "ok")
                           for p in (1, 2)):
                        per_phase[phase] = {"status": "skipped", "t": 0.0}
                        log_detail(f"  phase{phase} ({PHASE_NAMES[phase]}): "
                                   f"SKIPPED (earlier phase failed)")
                        continue
                    progress(f"[{stage}/{total_stages}] GPU  size={size_name} "
                             f"P={P} -- phase {phase} ({PHASE_NAMES[phase]})")
                    status, t = run_phase(cfg, phase, use_gpu=True,
                                          timeout_s=GPU_SAFETY_CAP_S,
                                          raw_path=raw_path)
                    per_phase[phase] = {"status": status, "t": t}
                    log_detail(f"  phase{phase} ({PHASE_NAMES[phase]}): "
                               f"{status} in {t:.1f}s  (raw: {raw_path})")
                gpu_results[(size_name, P)] = per_phase
                tot = sum(v["t"] for v in per_phase.values())
                log_detail(f"  GPU total (size={size_name} P={P}): {tot:.1f}s")

        # -- Pass 2: CPU (each phase capped at 2x its GPU counterpart) --
        for size in SIZES:
            for P in PARALLELISM:
                stage += 1
                size_name = size[0]
                progress(f"[{stage}/{total_stages}] CPU  size={size_name} P={P} "
                         f"-- starting")
                log_detail(f"--- STAGE {stage}/{total_stages} | CPU | "
                           f"size={size_name} | P={P} ---")
                wipe_working_dirs()
                cfg = _build_scaled_config(prod_cfg, size, P)
                gpu_pp = gpu_results.get((size_name, P), {})
                per_phase = cpu_results[(size_name, P)] = {}
                broke = False
                for phase in (1, 2, 3):
                    raw_path = os.path.join(
                        raw_dir, f"s{stage:02d}_cpu_{size_name}_P{P}_"
                                 f"p{phase}_{PHASE_NAMES[phase]}.log")
                    if broke:
                        per_phase[phase] = {"status": "skipped", "t": 0.0}
                        log_detail(f"  phase{phase} ({PHASE_NAMES[phase]}): "
                                   f"SKIPPED (earlier CPU phase did not finish)")
                        continue
                    g = gpu_pp.get(phase, {})
                    if g.get("status") == "ok" and g.get("t", 0) > 0:
                        cap = CPU_CAP_MULTIPLIER * g["t"]
                    else:
                        cap = CPU_FALLBACK_CAP_S
                        log_detail(f"  phase{phase}: no usable GPU baseline -> "
                                   f"fallback cap {cap:.0f}s")
                    progress(f"[{stage}/{total_stages}] CPU  size={size_name} "
                             f"P={P} -- phase {phase} ({PHASE_NAMES[phase]}) "
                             f"cap={cap:.0f}s")
                    status, t = run_phase(cfg, phase, use_gpu=False,
                                          timeout_s=cap, raw_path=raw_path)
                    per_phase[phase] = {"status": status, "t": t, "cap": cap}
                    log_detail(f"  phase{phase} ({PHASE_NAMES[phase]}): "
                               f"{status} in {t:.1f}s (cap {cap:.0f}s)  "
                               f"(raw: {raw_path})")
                    if status != "ok":
                        broke = True
                tot = sum(v["t"] for v in per_phase.values())
                log_detail(f"  CPU total (size={size_name} P={P}): {tot:.1f}s")

        # -- Summary table (both devices) --
        def _fmt(pp):
            cells, tot = [], 0.0
            for phase in (1, 2, 3):
                v = pp.get(phase, {})
                st, t = v.get("status", "-"), v.get("t", 0.0)
                tot += t
                cells.append(f"{t:8.1f}{'' if st == 'ok' else '*'}")
            return cells, tot

        log_detail("")
        log_detail("=== SUMMARY (seconds per phase) ===")
        log_detail(f"{'device':6} {'size':5} {'P':>2}  "
                   f"{'gto':>10} {'opponent':>10} {'mcts':>10} {'total':>10}")
        for dev, table in (("GPU", gpu_results), ("CPU", cpu_results)):
            for size in SIZES:
                for P in PARALLELISM:
                    cells, tot = _fmt(table.get((size[0], P), {}))
                    log_detail(f"{dev:6} {size[0]:5} {P:>2}  "
                               f"{cells[0]:>10} {cells[1]:>10} {cells[2]:>10} "
                               f"{tot:10.1f}")
        log_detail("  (* = phase did not finish cleanly: error/timeout/skipped)")
        log_detail("=== time_bench done ===")
        progress(f"time_bench: done. Detailed results in {detail_log_path}")

    finally:
        # Always restore the production config; keep the backup on disk.
        try:
            shutil.copyfile(backup_path, config_path)
            log_detail(f"restored production config from {backup_path}")
            progress(f"time_bench: restored production config "
                     f"(backup kept at {backup_path})")
        except Exception as e:
            progress(f"time_bench: FAILED to restore config: {e}. "
                     f"Restore manually from {backup_path}")
        _log_fh.close()


if __name__ == "__main__":
    run_benchmark()
